// ============================================================================
// Template Constants — Template system runtime defaults
// ============================================================================
/** Default color palettes per template */
export const TEMPLATE_COLORS = {
    notion: {
        light: {
            primary: '#2F3437',
            secondary: '#787774',
            accent: '#2383E2',
            background: '#FFFFFF',
            surface: '#F7F6F3',
            text: '#37352F',
            textSecondary: '#787774',
            border: '#E3E2DE',
        },
        dark: {
            primary: '#FFFFFF',
            secondary: '#9B9A97',
            accent: '#529CCA',
            background: '#191919',
            surface: '#202020',
            text: '#E3E2DE',
            textSecondary: '#9B9A97',
            border: '#373737',
        },
    },
    minimal: {
        light: {
            primary: '#111111',
            secondary: '#666666',
            accent: '#0066FF',
            background: '#FAFAFA',
            surface: '#FFFFFF',
            text: '#111111',
            textSecondary: '#888888',
            border: '#EEEEEE',
        },
        dark: {
            primary: '#FFFFFF',
            secondary: '#999999',
            accent: '#4D94FF',
            background: '#0A0A0A',
            surface: '#141414',
            text: '#EEEEEE',
            textSecondary: '#999999',
            border: '#222222',
        },
    },
    developer: {
        light: {
            primary: '#24292E',
            secondary: '#586069',
            accent: '#22C55E',
            background: '#FFFFFF',
            surface: '#F6F8FA',
            text: '#24292E',
            textSecondary: '#586069',
            border: '#E1E4E8',
        },
        dark: {
            primary: '#C9D1D9',
            secondary: '#8B949E',
            accent: '#4ADE80',
            background: '#0D1117',
            surface: '#161B22',
            text: '#C9D1D9',
            textSecondary: '#8B949E',
            border: '#30363D',
        },
    },
    modern: {
        light: {
            primary: '#1A1A2E',
            secondary: '#6C6C8A',
            accent: '#7C3AED',
            background: '#FAFBFC',
            surface: '#FFFFFF',
            text: '#1A1A2E',
            textSecondary: '#6C6C8A',
            border: '#E5E7EB',
        },
        dark: {
            primary: '#F1F5F9',
            secondary: '#94A3B8',
            accent: '#A78BFA',
            background: '#0F172A',
            surface: '#1E293B',
            text: '#F1F5F9',
            textSecondary: '#94A3B8',
            border: '#334155',
        },
    },
    creative: {
        light: {
            primary: '#1F2937',
            secondary: '#6B7280',
            accent: '#F59E0B',
            background: '#FFFBF5',
            surface: '#FFFFFF',
            text: '#1F2937',
            textSecondary: '#6B7280',
            border: '#F3E8D8',
        },
        dark: {
            primary: '#F9FAFB',
            secondary: '#9CA3AF',
            accent: '#FBBF24',
            background: '#111827',
            surface: '#1F2937',
            text: '#F9FAFB',
            textSecondary: '#9CA3AF',
            border: '#374151',
        },
    },
    editorial: {
        light: {
            primary: '#1B1B18',
            secondary: '#57534E',
            accent: '#B45309',
            background: '#FBFAF7',
            surface: '#FFFFFF',
            text: '#292524',
            textSecondary: '#78716C',
            border: '#E7E5E4',
        },
        dark: {
            primary: '#FAFAF9',
            secondary: '#D6D3D1',
            accent: '#F59E0B',
            background: '#1C1917',
            surface: '#292524',
            text: '#F5F5F4',
            textSecondary: '#A8A29E',
            border: '#44403C',
        },
    },
    neon: {
        light: {
            primary: '#082F49',
            secondary: '#475569',
            accent: '#06B6D4',
            background: '#F8FAFC',
            surface: '#FFFFFF',
            text: '#0F172A',
            textSecondary: '#64748B',
            border: '#CBD5E1',
        },
        dark: {
            primary: '#E0F2FE',
            secondary: '#94A3B8',
            accent: '#22D3EE',
            background: '#020617',
            surface: '#0F172A',
            text: '#E2E8F0',
            textSecondary: '#94A3B8',
            border: '#1E3A8A',
        },
    },
    executive: {
        light: {
            primary: '#111827',
            secondary: '#4B5563',
            accent: '#0F766E',
            background: '#F9FAFB',
            surface: '#FFFFFF',
            text: '#111827',
            textSecondary: '#6B7280',
            border: '#D1D5DB',
        },
        dark: {
            primary: '#F9FAFB',
            secondary: '#D1D5DB',
            accent: '#5EEAD4',
            background: '#111827',
            surface: '#1F2937',
            text: '#F9FAFB',
            textSecondary: '#9CA3AF',
            border: '#374151',
        },
    },
};
/** Default typography per template */
export const TEMPLATE_TYPOGRAPHY = {
    notion: {
        headingFont: "'Inter', -apple-system, sans-serif",
        bodyFont: "'Inter', -apple-system, sans-serif",
        headingWeight: 700,
        bodyWeight: 400,
        baseSize: 16,
        lineHeight: 1.6,
        letterSpacing: -0.01,
    },
    minimal: {
        headingFont: "'Outfit', sans-serif",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 600,
        bodyWeight: 400,
        baseSize: 16,
        lineHeight: 1.7,
        letterSpacing: 0,
    },
    developer: {
        headingFont: "'JetBrains Mono', monospace",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 700,
        bodyWeight: 400,
        baseSize: 15,
        lineHeight: 1.65,
        letterSpacing: 0,
    },
    modern: {
        headingFont: "'Outfit', sans-serif",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 800,
        bodyWeight: 400,
        baseSize: 16,
        lineHeight: 1.6,
        letterSpacing: -0.02,
    },
    creative: {
        headingFont: "'Playfair Display', serif",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 700,
        bodyWeight: 400,
        baseSize: 17,
        lineHeight: 1.7,
        letterSpacing: 0,
    },
    editorial: {
        headingFont: "'Playfair Display', serif",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 700,
        bodyWeight: 400,
        baseSize: 17,
        lineHeight: 1.75,
        letterSpacing: 0,
    },
    neon: {
        headingFont: "'JetBrains Mono', monospace",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 800,
        bodyWeight: 400,
        baseSize: 15,
        lineHeight: 1.65,
        letterSpacing: 0,
    },
    executive: {
        headingFont: "'Outfit', sans-serif",
        bodyFont: "'Inter', sans-serif",
        headingWeight: 700,
        bodyWeight: 400,
        baseSize: 16,
        lineHeight: 1.65,
        letterSpacing: 0,
    },
};
